@startuml
package "Контроль качества" <<component>> {
    [Управление заказами] --> [Заказ]

    [Отгрузка автомобиля]
    [Испытания автомобиля] --> [Дефект]
}

package "Планирование" <<component>> {
    [Производственный план]

    [Производственный план] --> [Загруженность конвейера]
    [Производственный план] --> [Доступность комплектующих]
    [Заказ] --> [Производственный план]
}

package "Производство" <<component>> {
    [Производство автомобилей] --> [Автомобиль]
[Производство автомобилей] --> [Конвейер]
    [Производство автомобилей] --> [Сборка кузова]
    [Производство автомобилей] --> [Покраска кузова]
    [Производство автомобилей] --> [Сборка комплектующих]
[Конвейер] --> [Возврат автомобиля]

}

package "Ремонт" <<component>> {
    [Рабочий]
    [Устранение дефекта] --> [Дефект]
    [Возврат автомобиля] --> [Контроль качества::Отгрузка автомобиля]
    [Рабочий]->[Назначение рабочего]
}

package "Ремонтная бригада" <<component>> {
[Назначение рабочего]
    [Назначение рабочего]-->[Бригадир]
}

[Производство автомобилей] --> [Конвейер]
[Дефект] --> [Ремонт::Устранение дефекта]
[Производственный план] --> [Производство автомобилей]
[Конвейер] --> [Сборка кузова]
[Сборка кузова] --> [Покраска кузова]
[Покраска кузова] --> [Сборка комплектующих]
[Сборка комплектующих] --> [Автомобиль]
@enduml