@startuml
[*] --> Ожидание

state Ожидание {
    [*] --> Дверь_закрыта
    Дверь_закрыта --> Дверь_открыта : Открыть дверь
    Дверь_открыта --> Дверь_закрыта : Закрыть дверь
}

state Настройка {
    [*] --> Установка_времени
    Установка_времени --> Установка_мощности : Выбрать время
    Установка_мощности --> Ожидание : Подтвердить настройку
}


state Пауза {
    [*] --> Дверь_закрыта
    Пауза_Дверь_закрыта --> Пауза_Дверь_открыта : Открыть дверь
    Пауза_Дверь_открыта --> Пауза_Дверь_закрыта : Закрыть дверь
}


Дверь_закрыта --> Готовка : Нажать "Старт"
Ожидание --> Настройка : Настроить микроволновку
Ожидание --> [*]: Выключить микроволновку
Готовка --> Готовка: Нажать "Старт", +30 секунд
Готовка --> Пауза_Дверь_открыта : Открыть дверь
Готовка --> Пауза_Дверь_закрыта : Нажать "Стоп"
Готовка --> Подать_сигнал : Таймер истёк
Подать_сигнал --> Ожидание : Завершить
Подать_сигнал --> Дверь_закрыта : Нажать "Стоп", выключить сигнал
Подать_сигнал --> Дверь_открыта : Открыть дверь, выключить сигнал
Пауза --> Готовка : Нажать "Старт"
Пауза --> Ожидание : Сброс

@enduml
